package com.maxrave.media3.audio

import androidx.media3.common.C
import androidx.media3.common.audio.AudioProcessor
import androidx.media3.common.audio.BaseAudioProcessor
import androidx.media3.common.util.UnstableApi
import com.maxrave.domain.data.player.AudioEffects
import com.maxrave.domain.data.player.ReverbImpulseResponse
import com.maxrave.domain.data.player.ReverbPreset
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Media3 [AudioProcessor] applying the convolution reverb.
 *
 * The impulse response is generated by `ReverbImpulseResponse` in `core/domain` and convolved by
 * [PartitionedConvolver], one instance per channel. Desktop hands the very same samples to ffmpeg's
 * `afir`; the reason both sides go through one generator is that a reverb dialled in on a phone has
 * to sound like the same room on a laptop, and the only way to guarantee that is for neither
 * platform to own the numbers. Android reaching for a system effect instead was never an option —
 * `android.media.audiofx.EnvironmentalReverb` is implemented by the device's audio HAL, so its
 * character varies by handset, exactly the trap the equalizer avoids by writing out its own biquads.
 *
 * Follows the shape [EqualizerAudioProcessor] established:
 * - the setting is read fresh on every buffer rather than captured, so an adjustment made while
 *   music is playing is audible immediately;
 * - one instance per player, since an [AudioProcessor] carries per-stream state, and they all read
 *   the same supplier so a single write covers both players of a crossfade;
 * - PCM 16-bit only, matching the rest of the chain and what the YouTube sources decode to.
 *
 * **Why the output is not the same length as the input.** Overlap-save produces nothing until a
 * whole 4096-frame partition has arrived, so a buffer can legitimately come out empty and the one
 * after it come out longer than it went in. Media3 allows this — a processor is asked to consume its
 * input and is then asked separately what it has — but it does mean the dry signal cannot simply be
 * blended with the wet as it arrives. Every input frame is queued in [dry] as it is fed to the
 * convolvers and dequeued in lock-step with their output, which keeps the two halves of the blend
 * sample-aligned by construction rather than by a delay constant somebody has to keep in step.
 */
@UnstableApi
class ConvolutionReverbAudioProcessor(
    private val effects: () -> AudioEffects,
) : BaseAudioProcessor() {
    private var sampleRate = 0
    private var channelCount = 0

    /** The effects object the state below was built from; compared by identity, never by value. */
    private var appliedEffects: AudioEffects? = null

    /** The preset the impulse was generated from, compared by value because an enum is a value. */
    private var appliedPreset: ReverbPreset? = null

    /** The rate the impulse was generated at, so a format change regenerates it. */
    private var impulseSampleRate = 0

    /** Wet level. Kept apart from [appliedPreset] so dragging the slider rebuilds nothing. */
    private var mix = 0f

    /** True while no reverb is selected, which is the whole of playback for most users. */
    private var bypass = true

    private var convolvers: Array<PartitionedConvolver> = emptyArray()

    /**
     * The dry signal, interleaved, waiting for its wet counterpart.
     *
     * Holds exactly the frames the convolvers have swallowed but not yet answered for: while the
     * effect is running that is `totalIn mod PARTITION_SIZE` frames, always fewer than one
     * partition; while bypassed it is empty. That equality is an invariant, and every path that
     * would break it has to put the frames somewhere rather than drop them — a preset change
     * replays this queue into the new convolvers, switching the effect off emits it dry, and only a
     * seek or a format change discards it, because there the audio either side of the cut is gone
     * anyway.
     */
    private var dry = ShortArray(0)
    private var dryHead = 0
    private var dryTail = 0

    /** Per-channel scratch: deinterleaved input on the way in, wet samples on the way back. */
    private var scratch: Array<FloatArray> = emptyArray()

    override fun onConfigure(inputAudioFormat: AudioProcessor.AudioFormat): AudioProcessor.AudioFormat {
        if (inputAudioFormat.encoding != C.ENCODING_PCM_16BIT) {
            return AudioProcessor.AudioFormat.NOT_SET
        }
        sampleRate = inputAudioFormat.sampleRate
        channelCount = inputAudioFormat.channelCount
        // Everything below depends on the rate or the channel count, so none of it survives a
        // format change. Clearing the applied markers is what forces the impulse to be regenerated
        // against the new rate on the first buffer rather than convolving at the wrong speed.
        convolvers = emptyArray()
        scratch = emptyArray()
        appliedEffects = null
        appliedPreset = null
        impulseSampleRate = 0
        clearDry()
        bypass = true
        return inputAudioFormat
    }

    // isActive() is deliberately NOT overridden, for the reason spelled out in
    // EqualizerAudioProcessor: the base class answers it from the format onConfigure just returned,
    // which is exactly the right question. Whether a reverb is selected has nothing to do with it —
    // that is what the bypass path below is for, and it has to stay reachable so switching the
    // effect on mid-track takes effect without reconfiguring the sink.

    override fun onFlush() {
        // The impulse survives a seek; the history must not. Whatever is in the convolvers is the
        // tail of audio the user has just skipped away from, and letting it ring over the new
        // position would sound like the old song bleeding into the new one.
        for (convolver in convolvers) {
            convolver.flush()
        }
        clearDry()
    }

    override fun onReset() {
        convolvers = emptyArray()
        scratch = emptyArray()
        appliedEffects = null
        appliedPreset = null
        impulseSampleRate = 0
        clearDry()
        sampleRate = 0
        channelCount = 0
        mix = 0f
        bypass = true
    }

    override fun queueInput(inputBuffer: ByteBuffer) {
        val remaining = inputBuffer.remaining()
        if (remaining == 0) return

        syncEffects()

        if (bypass) {
            // The backlog is whatever the convolvers had swallowed before the user switched the
            // effect off and never answered for — up to one partition, 85 ms. Those frames are real
            // input and still have to come out, so they are emitted dry, ahead of this buffer; only
            // the wet tail they would have grown is lost. Dropping them instead put an audible skip
            // at the moment the switch was flicked and left the output permanently shorter than the
            // input. In steady-state bypass the backlog is empty and this is the plain bulk copy it
            // looks like.
            val backlog = dryTail - dryHead
            val output = replaceOutputBuffer(backlog * SHORT_BYTES + remaining)
            while (dryHead < dryTail) {
                output.putShort(dry[dryHead])
                dryHead++
            }
            clearDry()
            // `replaceOutputBuffer` hands back this processor's own buffer while the input belongs
            // to the previous one in the chain, so the two are never the same object.
            output.put(inputBuffer)
            output.flip()
            return
        }

        inputBuffer.order(ByteOrder.nativeOrder())
        val frames = remaining / (channelCount * SHORT_BYTES)
        // A block can complete part-way through this buffer, so the convolvers can hand back up to
        // one whole partition more than was just written. Sizing for that up front means the scratch
        // is never reallocated between the write and the read.
        ensureScratch(frames + PartitionedConvolver.PARTITION_SIZE)
        ensureDryCapacity(frames * channelCount)

        for (frame in 0 until frames) {
            for (channel in 0 until channelCount) {
                val sample = inputBuffer.short
                scratch[channel][frame] = sample.toFloat()
                dry[dryTail] = sample
                dryTail++
            }
        }
        // PCM16 frames are always a whole number of bytes, so this should never fire. It is here
        // because the contract is to consume the whole input: leaving a byte behind makes the
        // pipeline re-offer the same buffer forever, having made no progress. There is nowhere
        // sensible to put a stray byte, since the output is not the same length as the input.
        while (inputBuffer.hasRemaining()) {
            inputBuffer.get()
        }

        for (channel in 0 until channelCount) {
            convolvers[channel].write(scratch[channel], 0, frames)
        }

        val produced = convolvers[0].availableOutput
        if (produced == 0) {
            // Everything fed is still inside the partition being filled. The input is consumed;
            // there is simply nothing finished to hand on. Replacing the buffer with an empty one
            // rather than leaving the previous contents in place keeps the state unambiguous.
            replaceOutputBuffer(0).flip()
            return
        }
        for (channel in 0 until channelCount) {
            // Every channel is fed the same count and partitions on the same boundaries, so a short
            // read means they have drifted apart. Failing loudly beats blending whatever the
            // scratch still held from the deinterleave pass, which would be silent corruption.
            val moved = convolvers[channel].read(scratch[channel], 0, produced)
            check(moved == produced) { "channel $channel returned $moved of $produced finished samples" }
        }
        blendIntoOutput(produced)
    }

    /**
     * Flush the last partial partition so a track does not lose its final 85 ms.
     *
     * Feeding silence up to the partition boundary is what makes the convolvers answer for the
     * samples still sitting inside them. Only the real frames are emitted — the padding produced
     * alongside them is the reverb tail of a track that has already ended, and Media3 has no buffer
     * left to put it in. [PartitionedConvolver.flush] drops it for the same reason.
     */
    override fun onQueueEndOfStream() {
        if (bypass || convolvers.isEmpty()) return
        val outstanding = dryFrames()
        if (outstanding == 0) return

        val padding = PartitionedConvolver.PARTITION_SIZE - outstanding
        ensureScratch(PartitionedConvolver.PARTITION_SIZE)
        for (channel in 0 until channelCount) {
            scratch[channel].fill(0f, 0, padding)
            convolvers[channel].write(scratch[channel], 0, padding)
            val moved = convolvers[channel].read(scratch[channel], 0, PartitionedConvolver.PARTITION_SIZE)
            check(moved == PartitionedConvolver.PARTITION_SIZE) {
                "channel $channel returned $moved samples of a padded block at end of stream"
            }
        }
        blendIntoOutput(outstanding)
    }

    /**
     * Write [frames] frames of `(1 - mix) * dry + mix * wet` to the output buffer.
     *
     * The dry samples come off the front of [dry] in the same interleaved order they went in, which
     * is what pairs each one with the wet sample computed from it. Both platforms blend with this
     * formula rather than, say, adding the wet at full level, so the mix slider means the same thing
     * on each — that is the whole reason it is written down twice instead of left to each backend.
     */
    private fun blendIntoOutput(frames: Int) {
        val output = replaceOutputBuffer(frames * channelCount * SHORT_BYTES)
        val wetLevel = mix
        val dryLevel = 1f - mix
        for (frame in 0 until frames) {
            for (channel in 0 until channelCount) {
                val blended = dry[dryHead].toFloat() * dryLevel + scratch[channel][frame] * wetLevel
                dryHead++
                output.putShort(blended.coerceIn(PCM16_MIN, PCM16_MAX).toInt().toShort())
            }
        }
        if (dryHead == dryTail) {
            dryHead = 0
            dryTail = 0
        }
        output.flip()
    }

    /** Re-read the setting, rebuilding only what actually changed. */
    private fun syncEffects() {
        val next = effects()
        if (next === appliedEffects) return
        appliedEffects = next

        val reverb = next.reverb
        if (reverb == null || channelCount <= 0 || sampleRate <= 0) {
            enterBypass()
            return
        }
        // Read before the rebuild check, so a mix-only change costs one float assignment. A reverb
        // at mix 0 still runs: it is a slider position the user may be dragging through, and
        // dropping into bypass would clear a four-second tail on the way past.
        mix = reverb.mix.coerceIn(0f, 1f)
        if (reverb.preset != appliedPreset || impulseSampleRate != sampleRate) {
            rebuild(reverb.preset)
        }
        bypass = false
    }

    /**
     * Generate [preset]'s impulse and build a convolver per channel.
     *
     * This runs on the audio thread, on the first buffer after the user picks a preset, and it is
     * not free: generating four seconds of impulse and transforming its 47 partitions costs tens of
     * milliseconds. It is absorbed because the sink is already holding hundreds of milliseconds of
     * audio ahead of it, and because a preset change is a deliberate, rare action rather than
     * something playback does on its own. Moving it to another thread would mean the buffer path
     * taking a lock, which is a worse trade for a cost paid once.
     *
     * Channel 0 takes the left impulse and channel 1 the right; the two are decorrelated, which is
     * what gives the tail its width. Anything past stereo takes the left one — a centre or surround
     * channel has no "other side" to be decorrelated from, and inventing one would smear it.
     */
    private fun rebuild(preset: ReverbPreset) {
        val impulse = ReverbImpulseResponse.generate(preset, sampleRate)
        val rebuilt =
            Array(channelCount) { channel ->
                PartitionedConvolver(if (channel == RIGHT_CHANNEL) impulse.right else impulse.left)
            }

        // The outgoing convolvers had swallowed these frames without answering for them, and the
        // dry queue is still holding their other halves. Replaying them into the new convolvers is
        // what keeps the two sides in lock-step across the swap; dropping them instead would leave
        // the dry queue permanently ahead, and every frame after the preset change would be blended
        // against the wet signal of a frame up to 85 ms older.
        val carried = dryFrames()
        if (carried > 0) {
            ensureScratch(carried)
            for (channel in 0 until channelCount) {
                for (frame in 0 until carried) {
                    scratch[channel][frame] = dry[dryHead + frame * channelCount + channel].toFloat()
                }
                rebuilt[channel].write(scratch[channel], 0, carried)
            }
        }

        convolvers = rebuilt
        appliedPreset = preset
        impulseSampleRate = sampleRate
    }

    /**
     * Stop processing, keeping the impulse but not the history.
     *
     * The convolvers survive so that switching the effect off and on again does not pay for the
     * impulse twice. Their history does not: the samples in there were convolved before the user
     * switched away, and ringing them out on top of the audio playing when the effect comes back
     * would splice a fragment of the past onto the present.
     *
     * The dry queue is deliberately NOT cleared here. It holds real input frames that have been
     * consumed but not yet emitted, and dropping them is an audible skip plus an output forever
     * shorter than the input. [queueInput] emits them dry on the very same buffer that lands here,
     * which is the last point at which they can still go anywhere.
     */
    private fun enterBypass() {
        if (!bypass) {
            for (convolver in convolvers) {
                convolver.reset()
            }
        }
        bypass = true
    }

    /** Frames — not samples — the dry queue is holding. */
    private fun dryFrames(): Int = if (channelCount <= 0) 0 else (dryTail - dryHead) / channelCount

    private fun clearDry() {
        dryHead = 0
        dryTail = 0
    }

    /**
     * Make room for [additional] more samples, compacting before growing.
     *
     * The queue drains almost completely on every buffer, so the head walks forward through a buffer
     * that is mostly free space; sliding the remainder back to the front is nearly always enough and
     * costs a copy of well under one partition.
     */
    private fun ensureDryCapacity(additional: Int) {
        if (dryTail + additional <= dry.size) return
        val kept = dryTail - dryHead
        if (kept + additional > dry.size) {
            var capacity = maxOf(dry.size, PartitionedConvolver.PARTITION_SIZE)
            while (capacity < kept + additional) {
                capacity *= 2
            }
            val grown = ShortArray(capacity)
            dry.copyInto(grown, destinationOffset = 0, startIndex = dryHead, endIndex = dryTail)
            dry = grown
        } else {
            dry.copyInto(dry, destinationOffset = 0, startIndex = dryHead, endIndex = dryTail)
        }
        dryHead = 0
        dryTail = kept
    }

    /** Grow the per-channel scratch to hold [frames]; its contents are never carried across. */
    private fun ensureScratch(frames: Int) {
        if (scratch.size == channelCount && scratch.isNotEmpty() && scratch[0].size >= frames) return
        scratch = Array(channelCount) { FloatArray(frames) }
    }

    private companion object {
        /** The channel that takes the right-hand impulse; everything else takes the left. */
        const val RIGHT_CHANNEL = 1

        const val SHORT_BYTES = 2

        const val PCM16_MIN = -32_768f
        const val PCM16_MAX = 32_767f
    }
}
